module.exports = Object.freeze({
    GALAXY_BARN: 'GALAXY_BARN',
    LUCKY_BARN: 'LUCKY_BARN',
    MT_HOOD_STAGE: 'MT_HOOD_STAGE',
    STARLIGHT_STAGE: 'STARLIGHT_STAGE',
    TREELINE_STAGE: 'TREELINE_STAGE',
    WOOD_STAGE: 'WOOD_STAGE',
})
