module.exports = Object.freeze({
    GALAXY_BARN_COLOR: '#9EC5E9',
    LUCKY_BARN_COLOR: '#FCEA7C',
    MT_HOOD_STAGE_COLOR: '#D26A62',
    STARLIGHT_STAGE_COLOR: '#B997FF',
    TREELINE_STAGE_COLOR: '#FF752A',
    WOOD_STAGE_COLOR: '#B2DE65',
    GALAXY_BARN: 'GALAXY_BARN',
    LUCKY_BARN: 'LUCKY_BARN',
    MT_HOOD_STAGE: 'MT_HOOD_STAGE',
    STARLIGHT_STAGE: 'STARLIGHT_STAGE',
    TREELINE_STAGE: 'TREELINE_STAGE',
    WOOD_STAGE: 'WOOD_STAGE',
})
